#include "engine.h"
#include <iostream>
#include <stdio.h>
#include <stdlib.h>


int16_t Engine::pawnPST(int loc){
    int square_index = this->board->color == WHITE ? loc : 63 - loc;
    if (square_index == 0) return 0;
    if (square_index == 1) return 0;
    if (square_index == 2) return 0;
    if (square_index == 3) return 0;
    if (square_index == 4) return 0;
    if (square_index == 5) return 0;
    if (square_index == 6) return 0;
    if (square_index == 7) return 0;
    if (square_index == 8) return 98;
    if (square_index == 9) return 134;
    if (square_index == 10) return 61;
    if (square_index == 11) return 95;
    if (square_index == 12) return 68;
    if (square_index == 13) return 126;
    if (square_index == 14) return 34;
    if (square_index == 15) return -11;
    if (square_index == 16) return -6;
    if (square_index == 17) return 7;
    if (square_index == 18) return 26;
    if (square_index == 19) return 31;
    if (square_index == 20) return 65;
    if (square_index == 21) return 56;
    if (square_index == 22) return 25;
    if (square_index == 23) return -20;
    if (square_index == 24) return -14;
    if (square_index == 25) return 13;
    if (square_index == 26) return 6;
    if (square_index == 27) return 21;
    if (square_index == 28) return 23;
    if (square_index == 29) return 12;
    if (square_index == 30) return 17;
    if (square_index == 31) return -23;
    if (square_index == 32) return -27;
    if (square_index == 33) return -2;
    if (square_index == 34) return -5;
    if (square_index == 35) return 12;
    if (square_index == 36) return 17;
    if (square_index == 37) return 6;
    if (square_index == 38) return 10;
    if (square_index == 39) return -25;
    if (square_index == 40) return -26;
    if (square_index == 41) return -4;
    if (square_index == 42) return -4;
    if (square_index == 43) return -10;
    if (square_index == 44) return 3;
    if (square_index == 45) return 3;
    if (square_index == 46) return 33;
    if (square_index == 47) return -12;
    if (square_index == 48) return -35;
    if (square_index == 49) return -1;
    if (square_index == 50) return -20;
    if (square_index == 51) return -23;
    if (square_index == 52) return -15;
    if (square_index == 53) return 24;
    if (square_index == 54) return 38;
    if (square_index == 55) return -22;
    if (square_index == 56) return 0;
    if (square_index == 57) return 0;
    if (square_index == 58) return 0;
    if (square_index == 59) return 0;
    if (square_index == 60) return 0;
    if (square_index == 61) return 0;
    if (square_index == 62) return 0;
    if (square_index == 63) return 0;

    // Return a default value for out-of-bounds indices
    return 0;

}

int16_t Engine::egPawnPST(int loc){
    int square_index = this->board->color == WHITE ? loc : 63 - loc;
    if (square_index == 0) return 0;
    if (square_index == 1) return 0;
    if (square_index == 2) return 0;
    if (square_index == 3) return 0;
    if (square_index == 4) return 0;
    if (square_index == 5) return 0;
    if (square_index == 6) return 0;
    if (square_index == 7) return 0;
    if (square_index == 8) return 178;
    if (square_index == 9) return 173;
    if (square_index == 10) return 158;
    if (square_index == 11) return 134;
    if (square_index == 12) return 147;
    if (square_index == 13) return 132;
    if (square_index == 14) return 165;
    if (square_index == 15) return 187;
    if (square_index == 16) return 94;
    if (square_index == 17) return 100;
    if (square_index == 18) return 85;
    if (square_index == 19) return 67;
    if (square_index == 20) return 56;
    if (square_index == 21) return 53;
    if (square_index == 22) return 82;
    if (square_index == 23) return 84;
    if (square_index == 24) return 32;
    if (square_index == 25) return 24;
    if (square_index == 26) return 13;
    if (square_index == 27) return 5;
    if (square_index == 28) return -2;
    if (square_index == 29) return 4;
    if (square_index == 30) return 17;
    if (square_index == 31) return 17;
    if (square_index == 32) return 13;
    if (square_index == 33) return 9;
    if (square_index == 34) return -3;
    if (square_index == 35) return -7;
    if (square_index == 36) return -7;
    if (square_index == 37) return -8;
    if (square_index == 38) return 3;
    if (square_index == 39) return -1;
    if (square_index == 40) return 4;
    if (square_index == 41) return 7;
    if (square_index == 42) return -6;
    if (square_index == 43) return 1;
    if (square_index == 44) return 0;
    if (square_index == 45) return -5;
    if (square_index == 46) return -1;
    if (square_index == 47) return -8;
    if (square_index == 48) return 13;
    if (square_index == 49) return 8;
    if (square_index == 50) return 8;
    if (square_index == 51) return 10;
    if (square_index == 52) return 13;
    if (square_index == 53) return 0;
    if (square_index == 54) return 2;
    if (square_index == 55) return -7;
    if (square_index == 56) return 0;
    if (square_index == 57) return 0;
    if (square_index == 58) return 0;
    if (square_index == 59) return 0;
    if (square_index == 60) return 0;
    if (square_index == 61) return 0;
    if (square_index == 62) return 0;
    if (square_index == 63) return 0;

    // Return a default value for out-of-bounds indices
    return 0;
}


int16_t Engine::knightPST(int loc) {
    int square_index = this->board->color == WHITE ? loc : 63 - loc;
    
    if (square_index == 0) return -167;
    if (square_index == 1) return -89;
    if (square_index == 2) return -34;
    if (square_index == 3) return -49;
    if (square_index == 4) return 61;
    if (square_index == 5) return -97;
    if (square_index == 6) return -15;
    if (square_index == 7) return -107;
    if (square_index == 8) return -73;
    if (square_index == 9) return -41;
    if (square_index == 10) return 72;
    if (square_index == 11) return 36;
    if (square_index == 12) return 23;
    if (square_index == 13) return 62;
    if (square_index == 14) return 7;
    if (square_index == 15) return -17;
    if (square_index == 16) return -47;
    if (square_index == 17) return 60;
    if (square_index == 18) return 37;
    if (square_index == 19) return 65;
    if (square_index == 20) return 84;
    if (square_index == 21) return 129;
    if (square_index == 22) return 73;
    if (square_index == 23) return 44;
    if (square_index == 24) return -9;
    if (square_index == 25) return 17;
    if (square_index == 26) return 19;
    if (square_index == 27) return 53;
    if (square_index == 28) return 37;
    if (square_index == 29) return 69;
    if (square_index == 30) return 18;
    if (square_index == 31) return 22;
    if (square_index == 32) return -13;
    if (square_index == 33) return 4;
    if (square_index == 34) return 16;
    if (square_index == 35) return 13;
    if (square_index == 36) return 28;
    if (square_index == 37) return 19;
    if (square_index == 38) return 21;
    if (square_index == 39) return -8;
    if (square_index == 40) return -23;
    if (square_index == 41) return -9;
    if (square_index == 42) return 12;
    if (square_index == 43) return 10;
    if (square_index == 44) return 19;
    if (square_index == 45) return 17;
    if (square_index == 46) return 25;
    if (square_index == 47) return -16;
    if (square_index == 48) return -29;
    if (square_index == 49) return -53;
    if (square_index == 50) return -12;
    if (square_index == 51) return -3;
    if (square_index == 52) return -1;
    if (square_index == 53) return 18;
    if (square_index == 54) return -14;
    if (square_index == 55) return -19;
    if (square_index == 56) return -105;
    if (square_index == 57) return -21;
    if (square_index == 58) return -58;
    if (square_index == 59) return -33;
    if (square_index == 60) return -17;
    if (square_index == 61) return -28;
    if (square_index == 62) return -19;
    if (square_index == 63) return -23;

    // Return a default value for out-of-bounds indices
    return 0;
}

int16_t Engine::egKnightPST(int loc) {
    int square_index = this->board->color == WHITE ? loc : 63 - loc;

    if (square_index == 0) return -58;
    if (square_index == 1) return -38;
    if (square_index == 2) return -13;
    if (square_index == 3) return -28;
    if (square_index == 4) return -31;
    if (square_index == 5) return -27;
    if (square_index == 6) return -63;
    if (square_index == 7) return -99;
    if (square_index == 8) return -25;
    if (square_index == 9) return -8;
    if (square_index == 10) return -25;
    if (square_index == 11) return -2;
    if (square_index == 12) return -9;
    if (square_index == 13) return -25;
    if (square_index == 14) return -24;
    if (square_index == 15) return -52;
    if (square_index == 16) return -24;
    if (square_index == 17) return -20;
    if (square_index == 18) return 10;
    if (square_index == 19) return 9;
    if (square_index == 20) return -1;
    if (square_index == 21) return -9;
    if (square_index == 22) return -19;
    if (square_index == 23) return -41;
    if (square_index == 24) return -17;
    if (square_index == 25) return 3;
    if (square_index == 26) return 22;
    if (square_index == 27) return 22;
    if (square_index == 28) return 22;
    if (square_index == 29) return 11;
    if (square_index == 30) return 8;
    if (square_index == 31) return -18;
    if (square_index == 32) return -18;
    if (square_index == 33) return -6;
    if (square_index == 34) return 16;
    if (square_index == 35) return 25;
    if (square_index == 36) return 16;
    if (square_index == 37) return 17;
    if (square_index == 38) return 4;
    if (square_index == 39) return -18;
    if (square_index == 40) return -23;
    if (square_index == 41) return -3;
    if (square_index == 42) return -1;
    if (square_index == 43) return 15;
    if (square_index == 44) return 10;
    if (square_index == 45) return -3;
    if (square_index == 46) return -20;
    if (square_index == 47) return -22;
    if (square_index == 48) return -42;
    if (square_index == 49) return -20;
    if (square_index == 50) return -10;
    if (square_index == 51) return -5;
    if (square_index == 52) return -2;
    if (square_index == 53) return -20;
    if (square_index == 54) return -23;
    if (square_index == 55) return -44;
    if (square_index == 56) return -29;
    if (square_index == 57) return -51;
    if (square_index == 58) return -23;
    if (square_index == 59) return -15;
    if (square_index == 60) return -22;
    if (square_index == 61) return -18;
    if (square_index == 62) return -50;
    if (square_index == 63) return -64;

    // Return a default value for out-of-bounds indices
    return 0;
}

int16_t Engine::bishopPST(int loc) {
    int square_index = this->board->color == WHITE ? loc : 63 - loc;
    
    if (square_index == 0) return -29;
    if (square_index == 1) return 4;
    if (square_index == 2) return -82;
    if (square_index == 3) return -37;
    if (square_index == 4) return -25;
    if (square_index == 5) return -42;
    if (square_index == 6) return 7;
    if (square_index == 7) return -8;
    if (square_index == 8) return -26;
    if (square_index == 9) return 16;
    if (square_index == 10) return -18;
    if (square_index == 11) return -13;
    if (square_index == 12) return 30;
    if (square_index == 13) return 59;
    if (square_index == 14) return 18;
    if (square_index == 15) return -47;
    if (square_index == 16) return -16;
    if (square_index == 17) return 37;
    if (square_index == 18) return 43;
    if (square_index == 19) return 40;
    if (square_index == 20) return 35;
    if (square_index == 21) return 50;
    if (square_index == 22) return 37;
    if (square_index == 23) return -2;
    if (square_index == 24) return -4;
    if (square_index == 25) return 5;
    if (square_index == 26) return 19;
    if (square_index == 27) return 50;
    if (square_index == 28) return 37;
    if (square_index == 29) return 37;
    if (square_index == 30) return 7;
    if (square_index == 31) return -2;
    if (square_index == 32) return -6;
    if (square_index == 33) return 13;
    if (square_index == 34) return 13;
    if (square_index == 35) return 26;
    if (square_index == 36) return 34;
    if (square_index == 37) return 12;
    if (square_index == 38) return 10;
    if (square_index == 39) return 4;
    if (square_index == 40) return 0;
    if (square_index == 41) return 15;
    if (square_index == 42) return 15;
    if (square_index == 43) return 15;
    if (square_index == 44) return 14;
    if (square_index == 45) return 27;
    if (square_index == 46) return 18;
    if (square_index == 47) return 10;
    if (square_index == 48) return 4;
    if (square_index == 49) return 15;
    if (square_index == 50) return 16;
    if (square_index == 51) return 0;
    if (square_index == 52) return 7;
    if (square_index == 53) return 21;
    if (square_index == 54) return 33;
    if (square_index == 55) return 1;
    if (square_index == 56) return -33;
    if (square_index == 57) return -3;
    if (square_index == 58) return -14;
    if (square_index == 59) return -21;
    if (square_index == 60) return -13;
    if (square_index == 61) return -12;
    if (square_index == 62) return -39;
    if (square_index == 63) return -21;

    // Return a default value for out-of-bounds indices
    return 0;
}

int16_t Engine::egBishopPST(int loc) {
    int square_index = this->board->color == WHITE ? loc : 63 - loc;
    
    if (square_index == 0) return -14;
    if (square_index == 1) return -21;
    if (square_index == 2) return -11;
    if (square_index == 3) return -8;
    if (square_index == 4) return -7;
    if (square_index == 5) return -9;
    if (square_index == 6) return -17;
    if (square_index == 7) return -24;
    if (square_index == 8) return -8;
    if (square_index == 9) return -4;
    if (square_index == 10) return 7;
    if (square_index == 11) return -12;
    if (square_index == 12) return -3;
    if (square_index == 13) return -13;
    if (square_index == 14) return -4;
    if (square_index == 15) return -14;
    if (square_index == 16) return 2;
    if (square_index == 17) return -8;
    if (square_index == 18) return 0;
    if (square_index == 19) return -1;
    if (square_index == 20) return -2;
    if (square_index == 21) return 6;
    if (square_index == 22) return 0;
    if (square_index == 23) return 4;
    if (square_index == 24) return -3;
    if (square_index == 25) return 9;
    if (square_index == 26) return 12;
    if (square_index == 27) return 9;
    if (square_index == 28) return 14;
    if (square_index == 29) return 10;
    if (square_index == 30) return 3;
    if (square_index == 31) return 2;
    if (square_index == 32) return -6;
    if (square_index == 33) return 3;
    if (square_index == 34) return 13;
    if (square_index == 35) return 19;
    if (square_index == 36) return 7;
    if (square_index == 37) return 10;
    if (square_index == 38) return -3;
    if (square_index == 39) return -9;
    if (square_index == 40) return -12;
    if (square_index == 41) return -3;
    if (square_index == 42) return 8;
    if (square_index == 43) return 10;
    if (square_index == 44) return 13;
    if (square_index == 45) return 3;
    if (square_index == 46) return -7;
    if (square_index == 47) return -15;
    if (square_index == 48) return -14;
    if (square_index == 49) return -18;
    if (square_index == 50) return -7;
    if (square_index == 51) return -1;
    if (square_index == 52) return 4;
    if (square_index == 53) return -9;
    if (square_index == 54) return -15;
    if (square_index == 55) return -27;
    if (square_index == 56) return -23;
    if (square_index == 57) return -9;
    if (square_index == 58) return -23;
    if (square_index == 59) return -5;
    if (square_index == 60) return -9;
    if (square_index == 61) return -16;
    if (square_index == 62) return -5;
    if (square_index == 63) return -17;

    // Return a default value for out-of-bounds indices
    return 0;
}

int16_t Engine::rookPST(int loc) {
    int square_index = this->board->color == WHITE ? loc : 63 - loc;
    
    if (square_index == 0) return 32;
    if (square_index == 1) return 42;
    if (square_index == 2) return 32;
    if (square_index == 3) return 51;
    if (square_index == 4) return 63;
    if (square_index == 5) return 9;
    if (square_index == 6) return 31;
    if (square_index == 7) return 43;
    if (square_index == 8) return 27;
    if (square_index == 9) return 32;
    if (square_index == 10) return 58;
    if (square_index == 11) return 62;
    if (square_index == 12) return 80;
    if (square_index == 13) return 67;
    if (square_index == 14) return 26;
    if (square_index == 15) return 44;
    if (square_index == 16) return -5;
    if (square_index == 17) return 19;
    if (square_index == 18) return 26;
    if (square_index == 19) return 36;
    if (square_index == 20) return 17;
    if (square_index == 21) return 45;
    if (square_index == 22) return 61;
    if (square_index == 23) return 16;
    if (square_index == 24) return -24;
    if (square_index == 25) return -11;
    if (square_index == 26) return 7;
    if (square_index == 27) return 26;
    if (square_index == 28) return 24;
    if (square_index == 29) return 35;
    if (square_index == 30) return -8;
    if (square_index == 31) return -20;
    if (square_index == 32) return -36;
    if (square_index == 33) return -26;
    if (square_index == 34) return -12;
    if (square_index == 35) return -1;
    if (square_index == 36) return 9;
    if (square_index == 37) return -7;
    if (square_index == 38) return 6;
    if (square_index == 39) return -23;
    if (square_index == 40) return -45;
    if (square_index == 41) return -25;
    if (square_index == 42) return -16;
    if (square_index == 43) return -17;
    if (square_index == 44) return 3;
    if (square_index == 45) return 0;
    if (square_index == 46) return -5;
    if (square_index == 47) return -33;
    if (square_index == 48) return -44;
    if (square_index == 49) return -16;
    if (square_index == 50) return -20;
    if (square_index == 51) return -9;
    if (square_index == 52) return -1;
    if (square_index == 53) return 11;
    if (square_index == 54) return -6;
    if (square_index == 55) return -71;
    if (square_index == 56) return -19;
    if (square_index == 57) return -13;
    if (square_index == 58) return 1;
    if (square_index == 59) return 17;
    if (square_index == 60) return 16;
    if (square_index == 61) return 7;
    if (square_index == 62) return -37;
    if (square_index == 63) return -26;

    // Return a default value for out-of-bounds indices
    return 0;
}

int16_t Engine::egRookPST(int loc) {
    int square_index = this->board->color == WHITE ? loc : 63 - loc;
    
    if (square_index == 0) return 13;
    if (square_index == 1) return 10;
    if (square_index == 2) return 18;
    if (square_index == 3) return 15;
    if (square_index == 4) return 12;
    if (square_index == 5) return 12;
    if (square_index == 6) return 8;
    if (square_index == 7) return 5;
    if (square_index == 8) return 11;
    if (square_index == 9) return 13;
    if (square_index == 10) return 13;
    if (square_index == 11) return 11;
    if (square_index == 12) return -3;
    if (square_index == 13) return 3;
    if (square_index == 14) return 8;
    if (square_index == 15) return 3;
    if (square_index == 16) return 7;
    if (square_index == 17) return 7;
    if (square_index == 18) return 7;
    if (square_index == 19) return 5;
    if (square_index == 20) return 4;
    if (square_index == 21) return -3;
    if (square_index == 22) return -5;
    if (square_index == 23) return -3;
    if (square_index == 24) return 4;
    if (square_index == 25) return 3;
    if (square_index == 26) return 13;
    if (square_index == 27) return 1;
    if (square_index == 28) return 2;
    if (square_index == 29) return 1;
    if (square_index == 30) return -1;
    if (square_index == 31) return 2;
    if (square_index == 32) return 3;
    if (square_index == 33) return 5;
    if (square_index == 34) return 8;
    if (square_index == 35) return 4;
    if (square_index == 36) return -5;
    if (square_index == 37) return -6;
    if (square_index == 38) return -8;
    if (square_index == 39) return -11;
    if (square_index == 40) return -4;
    if (square_index == 41) return 0;
    if (square_index == 42) return -5;
    if (square_index == 43) return -1;
    if (square_index == 44) return -7;
    if (square_index == 45) return -12;
    if (square_index == 46) return -8;
    if (square_index == 47) return -16;
    if (square_index == 48) return -6;
    if (square_index == 49) return -6;
    if (square_index == 50) return 0;
    if (square_index == 51) return 2;
    if (square_index == 52) return -9;
    if (square_index == 53) return -9;
    if (square_index == 54) return -11;
    if (square_index == 55) return -3;
    if (square_index == 56) return -9;
    if (square_index == 57) return 2;
    if (square_index == 58) return 3;
    if (square_index == 59) return -1;
    if (square_index == 60) return -5;
    if (square_index == 61) return -13;
    if (square_index == 62) return 4;
    if (square_index == 63) return -20;

    // Return a default value for out-of-bounds indices
    return 0;
}

int16_t Engine::queenPST(int loc) {
    int square_index = this->board->color == WHITE ? loc : 63 - loc;
    
    if (square_index == 0) return -28;
    if (square_index == 1) return 0;
    if (square_index == 2) return 29;
    if (square_index == 3) return 12;
    if (square_index == 4) return 59;
    if (square_index == 5) return 44;
    if (square_index == 6) return 43;
    if (square_index == 7) return 45;
    if (square_index == 8) return -24;
    if (square_index == 9) return -39;
    if (square_index == 10) return -5;
    if (square_index == 11) return 1;
    if (square_index == 12) return -16;
    if (square_index == 13) return 57;
    if (square_index == 14) return 28;
    if (square_index == 15) return 54;
    if (square_index == 16) return -13;
    if (square_index == 17) return -17;
    if (square_index == 18) return 7;
    if (square_index == 19) return 8;
    if (square_index == 20) return 29;
    if (square_index == 21) return 56;
    if (square_index == 22) return 47;
    if (square_index == 23) return 57;
    if (square_index == 24) return -27;
    if (square_index == 25) return -27;
    if (square_index == 26) return -16;
    if (square_index == 27) return -16;
    if (square_index == 28) return -1;
    if (square_index == 29) return 17;
    if (square_index == 30) return -2;
    if (square_index == 31) return 1;
    if (square_index == 32) return -9;
    if (square_index == 33) return -26;
    if (square_index == 34) return -9;
    if (square_index == 35) return -10;
    if (square_index == 36) return -2;
    if (square_index == 37) return -4;
    if (square_index == 38) return 3;
    if (square_index == 39) return -3;
    if (square_index == 40) return -14;
    if (square_index == 41) return 2;
    if (square_index == 42) return -11;
    if (square_index == 43) return -2;
    if (square_index == 44) return -5;
    if (square_index == 45) return 2;
    if (square_index == 46) return 14;
    if (square_index == 47) return 5;
    if (square_index == 48) return -35;
    if (square_index == 49) return -8;
    if (square_index == 50) return 11;
    if (square_index == 51) return 2;
    if (square_index == 52) return 8;
    if (square_index == 53) return 15;
    if (square_index == 54) return -3;
    if (square_index == 55) return 1;
    if (square_index == 56) return -1;
    if (square_index == 57) return -18;
    if (square_index == 58) return -9;
    if (square_index == 59) return 10;
    if (square_index == 60) return -15;
    if (square_index == 61) return -25;
    if (square_index == 62) return -31;
    if (square_index == 63) return -50;

    // Return a default value for out-of-bounds indices
    return 0;
}

int16_t Engine::egQueenPST(int loc) {
    int square_index = this->board->color == WHITE ? loc : 63 - loc;
    
    if (square_index == 0) return -9;
    if (square_index == 1) return 22;
    if (square_index == 2) return 22;
    if (square_index == 3) return 27;
    if (square_index == 4) return 27;
    if (square_index == 5) return 19;
    if (square_index == 6) return 10;
    if (square_index == 7) return 20;
    if (square_index == 8) return -17;
    if (square_index == 9) return 20;
    if (square_index == 10) return 32;
    if (square_index == 11) return 41;
    if (square_index == 12) return 58;
    if (square_index == 13) return 25;
    if (square_index == 14) return 30;
    if (square_index == 15) return 0;
    if (square_index == 16) return -20;
    if (square_index == 17) return 6;
    if (square_index == 18) return 9;
    if (square_index == 19) return 49;
    if (square_index == 20) return 47;
    if (square_index == 21) return 35;
    if (square_index == 22) return 19;
    if (square_index == 23) return 9;
    if (square_index == 24) return 3;
    if (square_index == 25) return 22;
    if (square_index == 26) return 24;
    if (square_index == 27) return 45;
    if (square_index == 28) return 57;
    if (square_index == 29) return 40;
    if (square_index == 30) return 57;
    if (square_index == 31) return 36;
    if (square_index == 32) return -18;
    if (square_index == 33) return 28;
    if (square_index == 34) return 19;
    if (square_index == 35) return 47;
    if (square_index == 36) return 31;
    if (square_index == 37) return 34;
    if (square_index == 38) return 39;
    if (square_index == 39) return 23;
    if (square_index == 40) return -16;
    if (square_index == 41) return -27;
    if (square_index == 42) return 15;
    if (square_index == 43) return 6;
    if (square_index == 44) return 9;
    if (square_index == 45) return 17;
    if (square_index == 46) return 10;
    if (square_index == 47) return 5;
    if (square_index == 48) return -22;
    if (square_index == 49) return -23;
    if (square_index == 50) return -30;
    if (square_index == 51) return -16;
    if (square_index == 52) return -16;
    if (square_index == 53) return -23;
    if (square_index == 54) return -36;
    if (square_index == 55) return -32;
    if (square_index == 56) return -33;
    if (square_index == 57) return -28;
    if (square_index == 58) return -22;
    if (square_index == 59) return -43;
    if (square_index == 60) return -5;
    if (square_index == 61) return -32;
    if (square_index == 62) return -20;
    if (square_index == 63) return -41;

    // Return a default value for out-of-bounds indices
    return 0;
}

int16_t Engine::kingPST(int loc) {
    int square_index = this->board->color == WHITE ? loc : 63 - loc;
    
    if (square_index == 0) return -65;
    if (square_index == 1) return 23;
    if (square_index == 2) return 16;
    if (square_index == 3) return -15;
    if (square_index == 4) return -56;
    if (square_index == 5) return -34;
    if (square_index == 6) return 2;
    if (square_index == 7) return 13;
    if (square_index == 8) return 29;
    if (square_index == 9) return -1;
    if (square_index == 10) return -20;
    if (square_index == 11) return -7;
    if (square_index == 12) return -8;
    if (square_index == 13) return -4;
    if (square_index == 14) return -38;
    if (square_index == 15) return -29;
    if (square_index == 16) return -9;
    if (square_index == 17) return 24;
    if (square_index == 18) return 2;
    if (square_index == 19) return -16;
    if (square_index == 20) return -20;
    if (square_index == 21) return 6;
    if (square_index == 22) return 22;
    if (square_index == 23) return -22;
    if (square_index == 24) return -17;
    if (square_index == 25) return -20;
    if (square_index == 26) return -12;
    if (square_index == 27) return -27;
    if (square_index == 28) return -30;
    if (square_index == 29) return -25;
    if (square_index == 30) return -14;
    if (square_index == 31) return -36;
    if (square_index == 32) return -49;
    if (square_index == 33) return -1;
    if (square_index == 34) return -27;
    if (square_index == 35) return -39;
    if (square_index == 36) return -46;
    if (square_index == 37) return -44;
    if (square_index == 38) return -33;
    if (square_index == 39) return -51;
    if (square_index == 40) return -14;
    if (square_index == 41) return -14;
    if (square_index == 42) return -22;
    if (square_index == 43) return -46;
    if (square_index == 44) return -44;
    if (square_index == 45) return -30;
    if (square_index == 46) return -15;
    if (square_index == 47) return -27;
    if (square_index == 48) return 1;
    if (square_index == 49) return 7;
    if (square_index == 50) return -8;
    if (square_index == 51) return -64;
    if (square_index == 52) return -43;
    if (square_index == 53) return -16;
    if (square_index == 54) return 9;
    if (square_index == 55) return 8;
    if (square_index == 56) return -15;
    if (square_index == 57) return 36;
    if (square_index == 58) return 12;
    if (square_index == 59) return -54;
    if (square_index == 60) return 8;
    if (square_index == 61) return -28;
    if (square_index == 62) return 24;
    if (square_index == 63) return 14;

    // Return a default value for out-of-bounds indices
    return 0;
}

int16_t Engine::egKingPST(int loc) {
    int square_index = this->board->color == WHITE ? loc : 63 - loc;
    
    if (square_index == 0) return -74;
    if (square_index == 1) return -35;
    if (square_index == 2) return -18;
    if (square_index == 3) return -18;
    if (square_index == 4) return -11;
    if (square_index == 5) return 15;
    if (square_index == 6) return 4;
    if (square_index == 7) return -17;
    if (square_index == 8) return -12;
    if (square_index == 9) return 17;
    if (square_index == 10) return 14;
    if (square_index == 11) return 17;
    if (square_index == 12) return 17;
    if (square_index == 13) return 38;
    if (square_index == 14) return 23;
    if (square_index == 15) return 11;
    if (square_index == 16) return 10;
    if (square_index == 17) return 17;
    if (square_index == 18) return 23;
    if (square_index == 19) return 15;
    if (square_index == 20) return 20;
    if (square_index == 21) return 45;
    if (square_index == 22) return 44;
    if (square_index == 23) return 13;
    if (square_index == 24) return -8;
    if (square_index == 25) return 22;
    if (square_index == 26) return 24;
    if (square_index == 27) return 27;
    if (square_index == 28) return 26;
    if (square_index == 29) return 33;
    if (square_index == 30) return 26;
    if (square_index == 31) return 3;
    if (square_index == 32) return -18;
    if (square_index == 33) return -4;
    if (square_index == 34) return 21;
    if (square_index == 35) return 24;
    if (square_index == 36) return 27;
    if (square_index == 37) return 23;
    if (square_index == 38) return 9;
    if (square_index == 39) return -11;
    if (square_index == 40) return -19;
    if (square_index == 41) return -3;
    if (square_index == 42) return 11;
    if (square_index == 43) return 21;
    if (square_index == 44) return 23;
    if (square_index == 45) return 16;
    if (square_index == 46) return 7;
    if (square_index == 47) return -9;
    if (square_index == 48) return -27;
    if (square_index == 49) return -11;
    if (square_index == 50) return 4;
    if (square_index == 51) return 13;
    if (square_index == 52) return 14;
    if (square_index == 53) return 4;
    if (square_index == 54) return -5;
    if (square_index == 55) return -17;
    if (square_index == 56) return -53;
    if (square_index == 57) return -34;
    if (square_index == 58) return -21;
    if (square_index == 59) return -11;
    if (square_index == 60) return -28;
    if (square_index == 61) return -14;
    if (square_index == 62) return -24;
    if (square_index == 63) return -43;

    // Return a default value for out-of-bounds indices
    return 0;
}


